services:
  - type: web
    name: radiance-clinic-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_SERVICE
        value: smtp
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        fromService:
          type: web
          name: radiance-clinic-backend
          envVarKey: GMAIL_USER
      - key: SMTP_PASS
        fromService:
          type: web
          name: radiance-clinic-backend
          envVarKey: GMAIL_PASS
      - key: EMAIL_FROM
        fromService:
          type: web
          name: radiance-clinic-backend
          envVarKey: GMAIL_USER
      - key: EMAIL_FROM_NAME
        value: Radiance Hair & Skin Clinic
      - key: BRAND_EMAIL
        value: drbrijsclinic@gmail.com
      - key: WEBSITE_URL
        value: https://radianceskin.org
